---
title: "Projects"

---
##Towards a Phenochronology: Reconstructing past Climate Using Historical Phenology Observations

This is my overarching project that encompasses several smaller efforts. 

Like many other hsitorical climate research projects, mululitple sources are used to produce and then validate the data. I am also collecting data for multiple locations throughout the southern United States.

###Recovering the Scientific Data of the Founding Fathers
many of the early figures in American history were avid naturalists. This came in many forms, including agricultural records on their farms and plantations, observations of flowering and migration dates for local species, as well as many other types of observations about their environment. In this project, we are extracting these observations into datasets that can be utilized in a variety of research fields. We are currently working on Thomas Jefferson's meteorlogical records and the diaries of George Washington. Thomas Jefferson's Garden Book hs been extracted into a data set and will be made available [here](https://github.com/gdb12/Historical-bioclimatology/tree/master/Thomas%20Jefferson/Garden%20Book). 

###Historical data Wrangling: Census point-to-polygon aggrigation for the Southern Farm Study, 1860

In the 1970's and 80's, William N. Parker and Robert E. Gallman collected a random samples of 1860 census returns from farm housholds from the slave ownng South. While the county level data is available, this is the only unaggrigated subset. This makes the data unique in agricultural, economic, and southern history. Unfortunately, data anlaysis has evelved significantly sense then, and it does not intereact well with modern systems. This is largely due to the laborious process of transcribing historical documents into a database. Due to the way the data was hand coded, it could not be intigrated with the Historical GIS' shape files or used in any spatial analysis of the data.

This python code wrangles the raw data and adds the state name from the published code book. This allows the data to be related to hsitorical county shapefiles. It also makes it possible to subset the data by state and county. This enables summary statistics to be produced from the data. The data and code can be found [here](https://github.com/gdb12/Census-point-to-polygon-aggrigation).